[package]
name = "lsplt-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lsplt"
path = "src/main.rs"

[dependencies]
lsplt-rs = { path = "../", version = "*" }
log = "^0.4.28"
log4rs = "1.4.0"
libc = "^0.2"